// Admin's slaves for the dashboard
const allSlavesData = [
  {
    id: 1,
    firstName: "Mario",
    lastName: "Rossi",
    email: "prova@Rossi.prova",
    phone: "3348558857",
    status: "pending",
    projects: [
      {
        id: 1,
        date: "2021-10-10",
        status: "completed",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 2,
        date: "2021-10-10",
        status: "new",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 3,
        date: "2021-10-10",
        status: "pending",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 4,
        date: "2021-10-10",
        status: "refunded",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 5,
        date: "2021-10-10",
        status: "failed",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
    ],
  },
  {
    id: 2,
    firstName: "Giovanni",
    lastName: "Verdi",
    email: "prova@Verdi.prova",
    phone: "3234558857",
    status: "banned",
    projects: [
      {
        id: 1,
        date: "2021-10-10",
        status: "completed",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 2,
        date: "2021-10-10",
        status: "new",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 3,
        date: "2021-10-10",
        status: "pending",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 4,
        date: "2021-10-10",
        status: "refunded",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 5,
        date: "2021-10-10",
        status: "failed",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
    ],
  },
  {
    id: 3,
    firstName: "Luca",
    lastName: "Gialli",
    email: "prova@Gialli.prova",
    phone: "3348552342",
    status: "active",
    projects: [
      {
        id: 1,
        date: "2021-10-10",
        status: "completed",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 2,
        date: "2021-10-10",
        status: "new",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 3,
        date: "2021-10-10",
        status: "pending",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 4,
        date: "2021-10-10",
        status: "refunded",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 5,
        date: "2021-10-10",
        status: "failed",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
    ],
  },
  {
    id: 4,
    firstName: "Mario",
    lastName: "Neri",
    email: "prova@Neri.prova",
    phone: "3348558857",
    status: "active",
    projects: [
      {
        id: 1,
        date: "2021-10-10",
        status: "completed",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 2,
        date: "2021-10-10",
        status: "new",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 3,
        date: "2021-10-10",
        status: "pending",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 4,
        date: "2021-10-10",
        status: "refunded",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 5,
        date: "2021-10-10",
        status: "failed",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
    ],
  },
  {
    id: 5,
    firstName: "Luca",
    lastName: "Viola",
    email: "prova@Neri.prova",
    phone: "3348558857",
    status: "active",
    projects: [
      {
        id: 1,
        date: "2021-10-10",
        status: "completed",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 2,
        date: "2021-10-10",
        status: "new",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 3,
        date: "2021-10-10",
        status: "pending",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 4,
        date: "2021-10-10",
        status: "refunded",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
      {
        id: 5,
        date: "2021-10-10",
        status: "failed",
        brand: "brand1",
        model: "Stelvio",
        generation: "2010",
        engine: "2.0",
        year: "2010",
        gearbox: "automatic",
        readingMethod: "Magicmotorsport",
        extraOptions: "Only options --adblue",
      },
    ],
  },
];
